"""add completion percentage to attendance

Revision ID: 1b4434f53d4b
Revises: 
Create Date: 2026-08-12 01:00:33.822888

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b4434f53d4b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completion_percentage', sa.Float(), nullable=True))
        batch_op.drop_constraint(batch_op.f('uq_user_date'), type_='unique')
        batch_op.create_unique_constraint('uq_user_attendance_date', ['user_id', 'date'])
        batch_op.drop_column('dhuhr')
        batch_op.drop_column('fajr')
        batch_op.drop_column('asr')
        batch_op.drop_column('isha')
        batch_op.drop_column('maghrib')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('maghrib', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('isha', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('asr', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('fajr', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('dhuhr', sa.VARCHAR(length=20), nullable=True))
        batch_op.drop_constraint('uq_user_attendance_date', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_user_date'), ['user_id', 'date'])
        batch_op.drop_column('completion_percentage')

    # ### end Alembic commands ###
